#!/usr/bin/env python3
"""One table of every evaluation: what was run, on which code and machine, and the scores.

    python bench/compare_runs.py                                   # print the table
    python bench/compare_runs.py --write results/reported/EXPERIMENTS.md

It reads the offline evaluations (results/offline/eval_*.json) and the live runs
(results/live/<time>/summary.json), and the published copies of both under
results/reported/, so the table also covers runs made on other machines. Older
results made before settings and provenance were recorded show "-" there.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
EVAL_NAME = re.compile(r"^eval_(asr|script)_(\d{8}_\d{6})(?:_(.+))?\.json$")


def _load(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def _num(v, pct=False):
    if v is None or v == "":
        return "-"
    try:
        return ("%.0f%%" % (float(v) * 100)) if pct else ("%.3f" % float(v)).rstrip("0").rstrip(".")
    except (TypeError, ValueError):
        return str(v)


def _short(s, n=8):
    return (s or "-")[:n]


def _weights(root):
    if not root or root.startswith("unknown"):
        return "-"
    return "4-bit" if "w4a16" in root else "FP8" if "FP8" in root else root.rsplit("/", 1)[-1][:18]


def offline_rows() -> list:
    rows, seen = [], set()
    for path in sorted(REPO.glob("results/offline/eval_*.json")) + sorted(REPO.glob("results/reported/**/eval_*.json")):
        m = EVAL_NAME.match(path.name)
        if not m or path.name in seen:
            continue
        d = _load(path)
        if not d or "summary" not in d:
            continue
        seen.add(path.name)
        s = d["summary"]
        st, pv = s.get("settings") or {}, s.get("provenance") or {}
        sc = (s.get("pass_by") or {}).get("disfluency:SELF_CORRECTION", "-")
        rows.append({
            "when": m.group(2), "tag": s.get("tag") or m.group(3) or "", "text": s.get("text", m.group(1)),
            "n": s.get("n"), "pass": s.get("pass@1"), "tool_f1": s.get("tool_f1"), "arg": s.get("arg_acc"),
            "resp": s.get("resp_qual"), "errors": s.get("errors"), "self_corr": sc.split(" ")[0],
            "temp": st.get("temperature", "-"), "seed": st.get("seed", "-"), "weights": _weights(st.get("weights")),
            "judge": "proxy" if "proxy" in str(s.get("judge", "")).lower() else
                     "none" if "exact" in str(s.get("judge", "")) else "gpt-4o",
            "commit": _short(pv.get("git_commit"), 7), "host": pv.get("host", "-"),
            "file": str(path.relative_to(REPO)).replace("\\", "/")})
    return sorted(rows, key=lambda r: r["when"])


def live_rows() -> list:
    rows, seen = [], set()
    for path in sorted(REPO.glob("results/live/*/summary.json")) + sorted(REPO.glob("results/reported/**/summary.json")):
        s = _load(path)
        if not s or "total" not in s:
            continue
        cfg = _load(path.parent / "run_config.json") or {}
        key = cfg.get("stamp") or path.parent.name
        if key in seen:
            continue
        seen.add(key)
        pv, gpu, agent = cfg.get("provenance") or {}, s.get("gpu") or {}, s.get("agent") or {}
        placement = pv.get("placement") or {}
        rows.append({
            "when": key, "provider": cfg.get("provider", "-"), "dry": "yes" if cfg.get("dry_run") else "",
            "n": s.get("total"), "pass": s.get("pass_at_1"), "tool_f1": s.get("tool_selection_f1"),
            "arg": s.get("argument_acc"), "resp": s.get("response_qual"), "turn": s.get("turn_take_rate"),
            "interrupt": s.get("interruption_rate"), "latency": s.get("task_completion_latency_mean_s"),
            "errors": agent.get("thinker_errors"), "ours_gib": gpu.get("ours_peak_gib") or "-",
            "layout": "split" if any(k in placement for k in ("DUET_LLM_GPUS", "DUET_AGENT_GPUS")) else
                      ("one GPU" if pv else "-"),
            "scoring": cfg.get("scoring_asr", "-"), "commit": _short(pv.get("git_commit") or s.get("git_commit"), 7),
            "host": pv.get("host", "-"), "folder": str(path.parent.relative_to(REPO)).replace("\\", "/")})
    return sorted(rows, key=lambda r: r["when"])


def table() -> str:
    off, live = offline_rows(), live_rows()
    out = ["# Experiment log", "",
           "Generated by `python bench/compare_runs.py`. Judge: `proxy` means the local model graded the "
           "answers (not the official gpt-4o); `none` means exact match only. Offline runs test the thinker "
           "on transcripts (`script` = the exact words, `asr` = what the agent's recognizer heard).", "",
           "## Offline evaluations (the thinker alone, all 100 recordings unless n says otherwise)", "",
           "| when | tag | text | n | Pass@1 | tool F1 | arg | resp | self-corr | errors | temp | seed | weights "
           "| judge | commit | host | file |",
           "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in off:
        out.append("| %s | %s | %s | %s | **%s** | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | `%s` |" % (
            r["when"], r["tag"] or "-", r["text"], r["n"], _num(r["pass"]), _num(r["tool_f1"]), _num(r["arg"]),
            _num(r["resp"]), r["self_corr"], r["errors"], r["temp"], r["seed"], r["weights"], r["judge"],
            r["commit"], r["host"], r["file"]))
    out += ["", "## Live benchmark runs (the whole agent, streamed in real time)", "",
            "| when | provider | dry | n | Pass@1 | tool F1 | arg | resp | turn-take | interrupt | task latency s "
            "| thinker errors | our GPU peak GiB | layout | scoring ASR | commit | host | folder |",
            "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in live:
        out.append("| %s | %s | %s | %s | **%s** | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | `%s` |" % (
            r["when"], r["provider"], r["dry"], r["n"], _num(r["pass"]), _num(r["tool_f1"]), _num(r["arg"]),
            _num(r["resp"]), _num(r["turn"], True), _num(r["interrupt"], True), _num(r["latency"]),
            _num(r["errors"]), r["ours_gib"], r["layout"], r["scoring"], r["commit"], r["host"], r["folder"]))
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", default="", help="also write the table to this Markdown file")
    args = ap.parse_args()
    text = table()
    print(text)
    if args.write:
        Path(args.write).parent.mkdir(parents=True, exist_ok=True)
        Path(args.write).write_text(text, encoding="utf-8")
        print("wrote", args.write, file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
